- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
        state: latest
        upgrade: dist
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: install updates (CentOS)
    yum:
      state: latest
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  roles:
    - nagios
